### ISSUE TITLE
No Test Coverage

### ISSUE THREAD

**Issue by hunter32292** [kneal/hello-world#1]
Hello,
I was trying to build your source code and noticed there isn't any test coverage, can you please fix this. 

Thanks,
John

**Comment by kneal** [comment]
hahaha, I'm using the Kelsey Hightower [nocode](https://github.com/kelseyhightower/nocode) approach to this project.

Can't test or build if I don't have any code 🙃

**Comment by hunter32292** [comment]
Ah my mistake, please disregard.
